name: parcial2024
version: 1.0.0.0

dependencies:
  - base

library:
  exposed-modules: Parcial
  source-dirs: src
  ghc-options: -Wall -Wno-type-defaults

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - parcial2024
      - hspec
