name: template
version: 1.0.0.0

dependencies:
  - base

library:
  exposed-modules: Main
  source-dirs: src
  ghc-options: -Wall -Wno-type-defaults

tests:
  test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - template
      - hspec
